// Registering app commands here generates `allow-<command>` permission
// identifiers that capabilities can grant. This is required because our
// production build serves the webview from a `http://127.0.0.1:<port>`
// origin (needed for SharedArrayBuffer support), which Tauri treats as
// "remote" content — and remote origins must explicitly opt into every
// invoke handler via capability permissions.
const COMMANDS: &[&str] = &[
    "send_message",
    "validate_pattern",
    "inspect_pattern",
    "analyze_arrangement",
    "critique_pattern",
    "critique_form",
    "genre_recipe",
    "get_pattern_history",
    "get_config",
    "clear_session",
    "open_file",
    "save_current",
    "save_as",
    "new_file",
    "is_dirty",
    "get_current_file",
    "get_recents",
    "clear_recents",
    "session_undo",
    "session_redo",
    "get_library_root",
    "set_library_root",
    "list_library",
    "create_library_folder",
    "create_library_file",
    "delete_library_path",
    "rename_library_path",
    "reveal_in_os",
    "autosave_session",
    "restore_session",
    "tray_set_playback",
    "import_midi",
    "inspect_midi",
    "save_midi_to_library",
    "get_user_settings",
    "set_user_settings",
    "set_provider_key",
    "has_provider_key",
    "xai_oauth_status",
    "xai_oauth_import_grok_build",
    "xai_oauth_start_login",
    "xai_oauth_poll_login",
    "xai_oauth_logout",
    "codex_oauth_status",
    "codex_oauth_import_cli",
    "codex_oauth_login",
    "codex_oauth_logout",
    "get_app_info",
    "write_binary_file",
    "export_audio",
    "export_wav",
    "export_midi",
    "list_snapshots",
    "read_snapshot",
    "get_logs",
    "clear_logs",
    "log_diagnostic",
    "diagnostic_dump",
    "set_dock_badge",
    "scan_sample_folder",
    "read_audio_file",
    "register_sound_banks",
    "list_sounds",
    "list_packs",
    "enable_pack",
    "disable_pack",
    "load_enabled_packs",
    "packs_dir",
    "install_pack_from_folder",
    "list_midi_input_devices",
    "start_midi_input_listening",
    "stop_midi_input_listening",
    "get_midi_input_status",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
