[package]
name = "dsl-eval"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "dsl-eval"
path = "main.rs"

[dependencies]
strudel-dsl = { path = "../../../../strudel-rs/crates/strudel-dsl" }
strudel-mini = { path = "../../../../strudel-rs/crates/strudel-mini", default-features = false }
strudel-core = { path = "../../../../strudel-rs/crates/strudel-core" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
