//! Render the genre map with computed coverage to `corpus/genres/_map.md`
//! (browsable in the repo; the `_` prefix keeps it out of the recipe loader
//! and corpus-check gating) and `_map.json` (data for the map artifact).
//! Run: `cargo run -p cycletron-gen --example gen_map`.

use cycletron_gen::map;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// Coverage is computed, never hand-maintained: `spec` when the registry
/// composes the name today, `recipe` when a researched `corpus/genres/<g>.md`
/// exists (checking the entry name, then the spec it resolves to).
fn recipe_path(genres_dir: &Path, entry: &map::MapEntry) -> Option<String> {
    let mut candidates = vec![entry.name.clone()];
    if let Some(spec) = entry.spec() {
        candidates.push(spec.name);
    }
    candidates
        .into_iter()
        .find(|name| genres_dir.join(format!("{name}.md")).exists())
        .map(|name| format!("{name}.md"))
}

fn json_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn main() {
    let genres_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("repo root")
        .join("corpus/genres");

    let families = map::families();
    let total: usize = families.iter().map(|f| f.genres.len()).sum();
    let mut spec_count = 0;
    let mut recipe_count = 0;

    let mut md = String::from(
        "# The Genre Map\n\n\
         GENERATED by `cargo run -p cycletron-gen --example gen_map` — do not edit.\n\
         Source of truth: `crates/cycletron-gen/src/map.rs` (see docs/GENRE_MAP_PLAN.md).\n\n\
         Coverage is computed: **spec** = `compose::by_name` plays it today; **recipe** =\n\
         a researched `corpus/genres/<g>.md` exists; blank = sketch awaiting Phase 2.\n\n",
    );
    let mut json = String::from("{\n  \"families\": [\n");

    for (fi, fam) in families.iter().enumerate() {
        writeln!(md, "## {}\n", fam.display).unwrap();
        writeln!(
            md,
            "| genre | bpm | mood | swing | drums | bass | spec | recipe |"
        )
        .unwrap();
        writeln!(md, "| --- | --- | --- | --- | --- | --- | --- | --- |").unwrap();
        writeln!(
            json,
            "    {{ \"name\": \"{}\", \"display\": \"{}\", \"genres\": [",
            json_escape(&fam.name),
            json_escape(&fam.display)
        )
        .unwrap();

        for (gi, e) in fam.genres.iter().enumerate() {
            let has_spec = e.spec().is_some();
            let recipe = recipe_path(&genres_dir, e);
            spec_count += usize::from(has_spec);
            recipe_count += usize::from(recipe.is_some());

            let drums = e
                .drums
                .iter()
                .map(|a| a.label())
                .collect::<Vec<_>>()
                .join(" + ");
            let drums_md = if drums.is_empty() {
                "—".to_string()
            } else {
                drums.clone()
            };
            let bass = e.bass.as_ref().map(|b| b.label()).unwrap_or("—");
            let swing = if e.swing > 0.0 {
                format!("{:.2}", e.swing)
            } else {
                "—".into()
            };
            writeln!(
                md,
                "| {} | {}–{} | {} | {} | {} | {} | {} | {} |",
                e.display,
                e.bpm.0,
                e.bpm.1,
                e.mood,
                swing,
                drums_md,
                bass,
                if has_spec { "✓" } else { "" },
                recipe.as_deref().map(|_| "✓").unwrap_or("")
            )
            .unwrap();

            let drum_labels = e
                .drums
                .iter()
                .map(|a| format!("\"{}\"", json_escape(&a.label())))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                json,
                "      {{ \"name\": \"{}\", \"display\": \"{}\", \"bpm\": [{}, {}], \
                 \"mood\": \"{}\", \"swing\": {}, \"drums\": [{}], \"bass\": {}, \
                 \"spec\": {}, \"recipe\": {} }}{}",
                json_escape(&e.name),
                json_escape(&e.display),
                e.bpm.0,
                e.bpm.1,
                json_escape(&e.mood),
                e.swing,
                drum_labels,
                e.bass
                    .as_ref()
                    .map(|b| format!("\"{}\"", b.label()))
                    .unwrap_or_else(|| "null".into()),
                has_spec,
                recipe
                    .as_deref()
                    .map(|r| format!("\"{}\"", json_escape(r)))
                    .unwrap_or_else(|| "null".into()),
                if gi + 1 < fam.genres.len() { "," } else { "" }
            )
            .unwrap();
        }
        md.push('\n');
        writeln!(
            json,
            "    ]}}{}",
            if fi + 1 < families.len() { "," } else { "" }
        )
        .unwrap();
    }

    writeln!(
        md,
        "---\n\n**{}** families · **{}** genres · **{}** spec-covered · **{}** recipe-covered",
        families.len(),
        total,
        spec_count,
        recipe_count
    )
    .unwrap();
    writeln!(
        json,
        "  ],\n  \"totals\": {{ \"families\": {}, \"genres\": {}, \"spec\": {}, \"recipe\": {} }}\n}}",
        families.len(),
        total,
        spec_count,
        recipe_count
    )
    .unwrap();

    std::fs::write(genres_dir.join("_map.md"), &md).expect("write _map.md");
    std::fs::write(genres_dir.join("_map.json"), &json).expect("write _map.json");
    println!(
        "wrote _map.md + _map.json: {} families, {total} genres, {spec_count} spec / {recipe_count} recipe covered",
        families.len()
    );
}
