//! `cycletron-gen` — corpus generators built from algorithmic-composition
//! primitives mined from the live-coding ecosystem (see `_references/`).
//!
//! Each generator is a pure function over integer/boolean value series; the
//! only strudel-specific step is *lowering* the series to a `.strudel` document
//! in the corpus house style. Keeping the generative core pure means it backs
//! both the `gen-pattern` CLI (offline corpus growth) and the agent's
//! `generate_pattern` tool, with one implementation. Everything emitted here is
//! designed to pass `validate_code` / `corpus-check`.
//!
//! Public entry points return a complete, ready-to-play `.strudel` document:
//!   [`infinity`]   melody   Per Nørgård's self-similar series
//!   [`hexbeat`]    rhythm   hex string → binary kick onsets
//!   [`numerals`]   harmony  Roman-numeral progression → diatonic chords
//!   [`palindrome`] form     mirror a motif into a symmetric phrase
//!   [`automaton`]  motion   elementary cellular automaton → evolving rhythm

pub mod compose;
pub mod factor;
pub mod genres;
pub mod grid;
pub mod map;
pub mod melody;
pub mod mini;
pub mod repair;
pub mod scale;
pub mod song;
pub mod spec;
pub mod verify;

/// Lowercase pitch-class names with sharps — strudel-rs note grammar (C4 = 60).
const PC_LOWER: [&str; 12] = [
    "c", "c#", "d", "d#", "e", "f", "f#", "g", "g#", "a", "a#", "b",
];
/// Uppercase pitch classes for `chord(...)` roots.
const PC_UPPER: [&str; 12] = [
    "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B",
];

// ---------------------------------------------------------------------------
// melody — Per Nørgård's infinity series
// ---------------------------------------------------------------------------

/// Per Nørgård's *infinity series*: a(0)=0, a(2n)=-a(n), a(2n+1)=a(n)+1.
/// A fractal sequence of semitone offsets — every other term reproduces the
/// whole line transposed.
pub fn infinity_series(count: usize) -> Vec<i32> {
    let mut a: Vec<i32> = Vec::with_capacity(count);
    for n in 0..count {
        let v = if n == 0 {
            0
        } else if n % 2 == 0 {
            -a[n / 2]
        } else {
            a[n / 2] + 1
        };
        a.push(v);
    }
    a
}

/// Lower semitone offsets to strudel note tokens relative to a root MIDI number.
pub fn offsets_to_notes(series: &[i32], root: i32) -> Vec<String> {
    series
        .iter()
        .map(|&off| {
            let midi = root + off;
            let name = PC_LOWER[midi.rem_euclid(12) as usize];
            let octave = midi.div_euclid(12) - 1;
            format!("{name}{octave}")
        })
        .collect()
}

/// Render an infinity-series melody as a `.strudel` document.
pub fn infinity(count: usize, root: i32) -> String {
    let series = infinity_series(count);
    let offsets = join_ints(&series);
    let pattern = offsets_to_notes(&series, root).join(" ");
    format!(
        "// Per Nørgård's \"infinity series\" (uendelighedsrækken) — a self-similar melody.\n\
         // Recurrence: a(0)=0, a(2n) = -a(n), a(2n+1) = a(n)+1, read as semitone\n\
         // offsets from a root. The line is fractal: every other note reproduces\n\
         // the whole series transposed.\n\
         // Generated by cycletron-gen (see _references/03). Offsets: {offsets}\n\
         setbpm(96);\n\
         \n\
         note(\"{pattern}\")\n\
         \x20 .s(\"triangle\")\n\
         \x20 .attack(0.01)\n\
         \x20 .release(0.3)\n\
         \x20 .gain(0.65)\n"
    )
}

// ---------------------------------------------------------------------------
// rhythm — hex beat
// ---------------------------------------------------------------------------

/// Decode a hex string into binary onsets, 4 bits per digit, MSB first.
/// e.g. "a4" → 1010 0100.
pub fn hex_beat(hex: &str) -> Result<Vec<bool>, String> {
    let mut bits = Vec::with_capacity(hex.len() * 4);
    for ch in hex.chars() {
        let nibble = ch
            .to_digit(16)
            .ok_or_else(|| format!("'{ch}' is not a hex digit"))?;
        for shift in (0..4).rev() {
            bits.push((nibble >> shift) & 1 == 1);
        }
    }
    Ok(bits)
}

/// Render a hex-beat drum pattern as a `.strudel` document.
pub fn hexbeat(hex: &str) -> Result<String, String> {
    let bits = hex_beat(hex)?;
    if !bits.iter().any(|&b| b) {
        return Err(format!("hex {hex:?} has no onsets — would be silent"));
    }
    let steps = bits
        .iter()
        .map(|&b| if b { "bd" } else { "~" })
        .collect::<Vec<_>>()
        .join(" ");
    let binary = bits
        .iter()
        .map(|&b| if b { '1' } else { '0' })
        .collect::<String>();
    Ok(format!(
        "// Hex beat \"{hex}\": each hex digit is four binary steps, 1 = kick onset.\n\
         // {hex} → {binary} ({} steps). A compact way to notate a whole bar of\n\
         // rhythm as a short string. Steady hats sit underneath for pulse.\n\
         setbpm(120);\n\
         \n\
         stack(\n\
         \x20 s(\"{steps}\"),\n\
         \x20 s(\"hh*8\").gain(0.45)\n\
         )\n",
        bits.len()
    ))
}

// ---------------------------------------------------------------------------
// harmony — Roman numerals → diatonic chords
// ---------------------------------------------------------------------------

/// Major-scale semitone offsets and the diatonic triad quality on each degree.
const MAJOR_DEGREES: [(i32, Quality); 7] = [
    (0, Quality::Maj),
    (2, Quality::Min),
    (4, Quality::Min),
    (5, Quality::Maj),
    (7, Quality::Maj),
    (9, Quality::Min),
    (11, Quality::Dim),
];

#[derive(Clone, Copy, PartialEq, Debug)]
enum Quality {
    Maj,
    Min,
    Dim,
}

impl Quality {
    fn suffix(self) -> &'static str {
        match self {
            Quality::Maj => "",
            Quality::Min => "m",
            Quality::Dim => "dim",
        }
    }
}

/// Parse a key root (e.g. "C", "F#", "Bb") into a pitch class 0..12.
pub fn parse_key(key: &str) -> Result<i32, String> {
    let mut chars = key.chars();
    let letter = chars.next().ok_or("empty key")?;
    let base = match letter.to_ascii_uppercase() {
        'C' => 0,
        'D' => 2,
        'E' => 4,
        'F' => 5,
        'G' => 7,
        'A' => 9,
        'B' => 11,
        other => return Err(format!("'{other}' is not a note letter")),
    };
    let acc: i32 = match chars.next() {
        Some('#') => 1,
        Some('b') => -1,
        None => 0,
        Some(other) => return Err(format!("'{other}' is not an accidental")),
    };
    Ok((base + acc).rem_euclid(12))
}

/// Parse a Roman numeral (I..VII, any case, optional °/o) to a degree index 0..7.
fn numeral_to_degree(token: &str) -> Result<usize, String> {
    let core: String = token
        .chars()
        .filter(|c| c.is_ascii_alphabetic())
        .map(|c| c.to_ascii_uppercase())
        .collect();
    match core.as_str() {
        "I" => Ok(0),
        "II" => Ok(1),
        "III" => Ok(2),
        "IV" => Ok(3),
        "V" => Ok(4),
        "VI" => Ok(5),
        "VII" => Ok(6),
        other => Err(format!("'{other}' is not a Roman numeral I–VII")),
    }
}

/// Map a numeral progression in a major key to `chord(...)` symbols (e.g. "Dm").
pub fn numerals_to_chords(key_pc: i32, numerals: &str) -> Result<Vec<String>, String> {
    numerals
        .split_whitespace()
        .map(|tok| {
            let degree = numeral_to_degree(tok)?;
            let (offset, quality) = MAJOR_DEGREES[degree];
            let root = PC_UPPER[(key_pc + offset).rem_euclid(12) as usize];
            Ok(format!("{root}{}", quality.suffix()))
        })
        .collect()
}

/// Render a Roman-numeral chord progression as a `.strudel` document.
pub fn numerals(key: &str, numerals: &str) -> Result<String, String> {
    let key_pc = parse_key(key)?;
    let chords = numerals_to_chords(key_pc, numerals)?;
    let symbols = chords.join(" ");
    let key_name = PC_UPPER[key_pc as usize];
    Ok(format!(
        "// Diatonic triads from Roman numerals in {key_name} major: {numerals} → {symbols}.\n\
         // One chord per cycle via slowcat <...>. Quality follows the major scale\n\
         // (I,IV,V major; ii,iii,vi minor; vii° diminished).\n\
         setbpm(90);\n\
         \n\
         chord(\"<{symbols}>\")\n\
         \x20 .s(\"sawtooth\")\n\
         \x20 .cutoff(1200)\n\
         \x20 .attack(0.05)\n\
         \x20 .release(0.6)\n\
         \x20 .gain(0.55)\n"
    ))
}

// ---------------------------------------------------------------------------
// form — palindrome
// ---------------------------------------------------------------------------

/// Mirror a motif into a palindrome, reflecting around the final element so
/// it is not duplicated: [a b c d] → [a b c d c b a].
pub fn palindrome_tokens(motif: &[String]) -> Vec<String> {
    let mut out = motif.to_vec();
    out.extend(motif.iter().rev().skip(1).cloned());
    out
}

/// Render a palindromic motif as a `.strudel` document.
pub fn palindrome(motif: &str) -> String {
    let tokens: Vec<String> = motif.split_whitespace().map(String::from).collect();
    let mirrored = palindrome_tokens(&tokens).join(" ");
    format!(
        "// Palindromic motif: the phrase reads the same forwards and backwards.\n\
         // Base motif \"{motif}\" reflected around its last note — a symmetric\n\
         // arch form. Mirroring is one of total-serialism's transforms.\n\
         setbpm(96);\n\
         \n\
         note(\"{mirrored}\")\n\
         \x20 .s(\"triangle\")\n\
         \x20 .attack(0.01)\n\
         \x20 .release(0.3)\n\
         \x20 .gain(0.6)\n"
    )
}

// ---------------------------------------------------------------------------
// motion — elementary cellular automaton
// ---------------------------------------------------------------------------

/// Evolve an elementary cellular automaton (Wolfram numbering) from a single
/// centre seed, wrapping at the edges. Returns `gens` rows of `width` cells.
pub fn ca_rows(rule: u8, width: usize, gens: usize) -> Vec<Vec<bool>> {
    let mut row = vec![false; width];
    row[width / 2] = true;
    let mut rows = Vec::with_capacity(gens);
    for _ in 0..gens {
        rows.push(row.clone());
        let mut next = vec![false; width];
        for i in 0..width {
            let l = row[(i + width - 1) % width];
            let c = row[i];
            let r = row[(i + 1) % width];
            let idx = (l as u8) << 2 | (c as u8) << 1 | (r as u8);
            next[i] = (rule >> idx) & 1 == 1;
        }
        row = next;
    }
    rows
}

/// Render a cellular-automaton-driven evolving rhythm as a `.strudel` document.
pub fn automaton(rule: u8, width: usize, gens: usize) -> Result<String, String> {
    if width == 0 || gens == 0 {
        return Err("width and gens must be > 0".to_string());
    }
    let rows = ca_rows(rule, width, gens);
    if rows.first().is_none_or(|r| !r.iter().any(|&c| c)) {
        return Err("seed row is silent".to_string());
    }
    // Each row becomes a bracketed step group; slowcat them so the rhythm
    // reorganises every cycle.
    let groups = rows
        .iter()
        .map(|row| {
            let steps = row
                .iter()
                .map(|&c| if c { "hh" } else { "~" })
                .collect::<Vec<_>>()
                .join(" ");
            format!("[{steps}]")
        })
        .collect::<Vec<_>>()
        .join(" ");
    Ok(format!(
        "// Elementary cellular automaton (Wolfram rule {rule}) drives an evolving\n\
         // hat line. A single seed cell evolves over {gens} generations; each row\n\
         // becomes one cycle, so the rhythm reorganises itself every bar.\n\
         setbpm(120);\n\
         \n\
         stack(\n\
         \x20 s(\"bd*4\"),\n\
         \x20 s(\"<{groups}>\").gain(0.5)\n\
         )\n"
    ))
}

// ---------------------------------------------------------------------------

fn join_ints(xs: &[i32]) -> String {
    xs.iter()
        .map(|n| n.to_string())
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn infinity_matches_known_prefix() {
        assert_eq!(
            infinity_series(16),
            vec![0, 1, -1, 2, 1, 0, -2, 3, -1, 2, 0, 1, 2, -1, -3, 4]
        );
    }

    #[test]
    fn infinity_even_indices_are_inverted_whole() {
        let a = infinity_series(16);
        for n in 0..8 {
            assert_eq!(a[2 * n], -a[n]);
        }
    }

    #[test]
    fn lowering_spells_root_and_offsets() {
        assert_eq!(
            offsets_to_notes(&[0, 1, -1, 4], 60),
            vec!["c4", "c#4", "b3", "e4"]
        );
    }

    #[test]
    fn hex_beat_decodes_nibbles_msb_first() {
        assert_eq!(
            hex_beat("a4").unwrap(),
            vec![true, false, true, false, false, true, false, false]
        );
    }

    #[test]
    fn numerals_resolve_diatonic_qualities_in_c() {
        let chords = numerals_to_chords(parse_key("C").unwrap(), "ii V I vi").unwrap();
        assert_eq!(chords, vec!["Dm", "G", "C", "Am"]);
    }

    #[test]
    fn numerals_transpose_to_other_keys() {
        let chords = numerals_to_chords(parse_key("G").unwrap(), "ii V I").unwrap();
        assert_eq!(chords, vec!["Am", "D", "G"]);
    }

    #[test]
    fn palindrome_reflects_around_last_element() {
        let motif: Vec<String> = ["a", "b", "c", "d"].iter().map(|s| s.to_string()).collect();
        assert_eq!(
            palindrome_tokens(&motif),
            vec!["a", "b", "c", "d", "c", "b", "a"]
        );
    }

    #[test]
    fn rule90_seed_row_fans_out() {
        let rows = ca_rows(90, 8, 4);
        assert_eq!(rows[0].iter().filter(|&&c| c).count(), 1);
        assert_eq!(rows[1].iter().filter(|&&c| c).count(), 2);
    }

    #[test]
    fn rendered_documents_have_setbpm_and_body() {
        for doc in [
            infinity(16, 60),
            hexbeat("a4f2").unwrap(),
            numerals("C", "ii V I vi").unwrap(),
            palindrome("c4 e4 g4 b4"),
            automaton(90, 8, 4).unwrap(),
        ] {
            assert!(doc.contains("setbpm("), "missing setbpm: {doc}");
        }
    }
}
